Add todo pull
kiall/android-tvheadend pull request #188
Opened 2017-06-09 14:39 UTC by cyberjacob

Add TODOs. All stuff I can probably manage

2017-06-10 13:18 UTC, kiall requested changes

2017-06-10 13:18 UTC, kiall commented on app/src/main/java/ie/macinnes/tvheadend/sync/EpgSyncTask.java
> +        //TODO: Why do these both do the same thing?
They don't do the same thing :)

The first branch (where `mInitialSyncCompleted == true`) will - once the initial sync has completed - flush every channel operation as it comes in.

The second branch (!IS_BRAVIA && mPendingChannelOps.size() >= 100) will - until the initial sync has completed - flush every 100 channel operations. Unless you're on a Sony Bravia, in that case, we wait for every channel to arrive before flushing so we can sort them correctly to workaround a Sony issue.

2017-06-10 13:18 UTC, kiall commented on app/src/main/java/ie/macinnes/tvheadend/player/HtspDataSource.java
> +                //TODO: Clean up and re-throw, or java will do it anway
There's nothing to clean up or rethrow here, when we're InterruptedException, it's expected we just stop waiting for data - and return 0 (as we read no data into the buffer)

2017-06-10 13:18 UTC, kiall commented on app/src/main/java/ie/macinnes/tvheadend/player/Player.java
> +    //TODO: Never used, check if this is still needed
This is groundwork for full timeshift support :)

2017-06-10 13:18 UTC, kiall commented on app/src/main/java/ie/macinnes/tvheadend/player/Player.java
> +    //TODO: Never used, check if this is still needed
This is groundwork for full timeshift support :)

2017-08-29 15:13 UTC, cyberjacob commented
Closing as nothing to do any more :)

2017-08-29 15:13 UTC, closed without merging